struct Data {
    width: f32,
    height: f32,
    scale_factor: f32,
    time_elapsed: f32,
    frame_number: u32,
    camx: f32,
    camy: f32,
    camz: f32,
    lookx: f32,
    looky: f32,
    lookz: f32,
    fov: f32,
    sky_color_top_r: f32,
    sky_color_top_g: f32,
    sky_color_top_b: f32,
    sky_color_bottom_r: f32,
    sky_color_bottom_g: f32,
    sky_color_bottom_b: f32,
};
